In [1]:
import numpy as np

a = np.array([1, 2, 3]) # могут содержать любые другие данные
b = np.array([[1, 2, 3], [3, 3, 3]])
c = np.array([[[1, 2, 3], [3, 4, 5], [4, 4, 4]]])
for i in range(3):
    d = [a, b, c]
    print("\n",d[i])


 [1 2 3]

 [[1 2 3]
 [3 3 3]]

 [[[1 2 3]
  [3 4 5]
  [4 4 4]]]


Массивы NumPy обладают более широкими возможностями, 
чем встроенные списки Python. Например, над двумя массивами NumPy можно выполнять 
простейшие арифметические операции +, –, * и /. Эти поэлементные операции над массивами
(например, сложение их с помощью оператора +) 
заключаются в выполнении соответствующей операции над каждым из элементов массива
a с соответствующим элементом массива b. 
Другими словами, поэлементная операция агрегирует два элемента, 
расположенных на одинаковых местах в массивах a и b. 

In [2]:
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [2, 0, 0]])
b = np.array([[1, 1, 1],
            [1, 1, 2],
            [1, 1, 2]])
print(a + b)
print( a - b)
print( a * b)
print( a / b)

[[2 1 1]
 [2 2 3]
 [3 1 2]]
[[ 0 -1 -1]
 [ 0  0 -1]
 [ 1 -1 -2]]
[[1 0 0]
 [1 1 2]
 [2 0 0]]
[[1.  0.  0. ]
 [1.  1.  0.5]
 [2.  0.  0. ]]


При использовании операторов NumPy к массивам целых чисел библиотека пытается сгенерировать 
в качестве результата также массив целых чисел. 
Только при делении двух массивов целых чисел с помощью оператора деления,
a / b, результат будет массивом чисел с плавающей точкой, 
на что указывают десятичные точки: 1., 0. и 0.5.

NumPy предоставляет и многие другие средства для работы с массивами, 
включая функцию np.max(), вычисляющую максимальное из всех значений массива NumPy. 
Функция np.min() вычисляет минимальное из всех значений массива NumPy. 
Функция np.average() вычисляет среднее значение массива NumPy.

In [3]:
print(np.max(a))
print(np.min(a))
print(np.average(a))

2
0
0.6666666666666666


Похоже, что у Боба последние три года самая высокая зарплата из наших троих друзей. 
Но приносит ли он домой действительно больше всех денег 
с учетом индивидуальных ставок налогообложения?

In [4]:
## Данные: годовые зарплаты в тысячах долларов (за 2017, 2018 и 2019 гг.)
alice = [99, 101, 103]
bob = [110, 108, 105]
tim = [90, 88, 85]

salaries = np.array([alice, bob, tim])
taxation = np.array([[0.2, 0.25, 0.22],
                    [0.4, 0.5, 0.5],
                    [0.1, 0.2, 0.1]]) # индивидуальныу ставки налогообложения
### logic
max_income = np.max(salaries - salaries * taxation)
### out
print('самая большая прибыль у кого-то', max_income)
print(salaries - salaries * taxation)

самая большая прибыль у кого-то 81.0
[[79.2  75.75 80.34]
 [66.   54.   52.5 ]
 [81.   70.4  76.5 ]]


Предыдущий фрагмент кода выводит максимальное значение этого итогового массива. 
Функция np.max() просто находит в массиве максимальное значение, 
которое мы затем сохраняем в переменной max_income. 
Максимальным значением оказывается доход Тима, равный 90 000 долларов в 2017 году, 
облагаемый налогом всего 10 % — результат выполнения однострочника равен 81. 
(опять же, точка в конце указывает на тип данных float).

Например, операция доступа по индексу y[0,1,2] служит для обращения к первому
элементу первой оси координат, второму элементу второй оси координат и 
третьему элементу третьей оси координат. 
Учтите, что такой синтаксис не подходит для многомерных списков Python. 
Тоесть обращается как к Матрице.

In [5]:
import numpy as np
a = np.array([55, 56, 57, 58, 59, 60, 61])
print(a)
print(a[:])
print(a[2:])
print(a[2:4])
print(a[::-1])
print(a[:1:-2])
print(a[-1:1:-2])

[55 56 57 58 59 60 61]
[55 56 57 58 59 60 61]
[57 58 59 60 61]
[57 58]
[61 60 59 58 57 56 55]
[61 59 57]
[61 59 57]
