In [3]:
import numpy as np 
import random as rn
a = np.array([[0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]])

print(a[:, 2]) # третий столбец
print(a[1, :]) # вторая строка 
print(a[2, :]) # третья строка 
print(a[0:2, 1:2]) # третья строка, 
print(a[:, :-1]) # за исключением, здесь не работает чтение наоборот 
print(a[-1:, -1:]) # за исключением, здесь не работает чтение наоборот   
print(a[-1:, :]) # за исключением, здесь не работает чтение наоборот  
print(a[:, -1:]) # за исключением, здесь не работает чтение наоборот  
print(a[:-2]) # a[:-2, :] аналогично 
#остановился на транслировании 


[ 2  6 10 14]
[4 5 6 7]
[ 8  9 10 11]
[[1]
 [5]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
[[15]]
[[12 13 14 15]]
[[ 3]
 [ 7]
 [11]
 [15]]
[[0 1 2 3]
 [4 5 6 7]]


In [6]:
print("Исходный массив",a[:, :])
print("Развернутый массив",a[:, ::-1]) # все таки разворачивается ))) 

Исходный массив [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Развернутый массив [[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]
