Транслирование (broadcasting) означает автоматический процесс приведения двух массивов NumPy к одной форме для применения определенных поэлементных операций. Транслирование тесно связано с атрибутом формы массивов NumPy, который, в свою очередь, тесно связан с понятием осей координат. Так что займемся изучением осей координат, форм и транслирования.

In [1]:
import numpy as np 

a = np.array([1, 2, 3, 4])
print(a.ndim)  # колличевство осей координат

1


In [2]:
b = np.array([[2,1,2], [3,2,3], [4,3,4]])
print(b.ndim)# соотвественно две 

2


In [3]:
c = np.array([[[1, 2, 3], [2, 3 , 4], [3, 4, 5],
               [1, 2, 3], [2, 3, 5], [3, 4, 6]]])
print(c.ndim)# соотвественно три 

3


При повышении размерности массива (например, при переходе от двумерного к трехмерному массиву) новая ось становится осью 0, а i-я ось массива более низкой размерности становится (i + 1)-й осью массива более высокой размерности.

In [4]:
print(a.shape) # колличевство столбцов

(4,)


In [5]:
print(b.shape) # стобцов и строк

(3, 3)


In [8]:
c = np.array([[[1, 2, 3], [2, 3, 4], [3, 4, 5]],
[[1, 2, 4], [2, 3, 5], [3, 4, 6]]])
print(c.shape) 

(2, 3, 3)


массив c — трехмерный, так что его кортеж shape содержит три элемента, по одному для каждой оси. Ось 0 содержит два элемента (каждый элемент — двумерный массив), ось 1 — три элемента (каждый из которых — одномерный массив), а ось 2 — три элемента (каждый из которых — целочисленное значение).
Очень грубо можно назвать вложенным графом с понижающейся размерностью на каждом уровне дерева

Например, оператор умножения *, примененный к массивам NumPy, обычно выполняет поэлементное умножение. Но что произойдет, если данные слева и справа от него не совпадают по форме (скажем, операнд слева представляет собой массив NumPy, а справа — значение с плавающей точкой)? В этом случае NumPy не выдаст ошибку, а автоматически создаст новый массив из данных, расположенных справа. Размер и размерность этого нового массива — те же, что и у массива слева, он содержит те же значения с плавающей точкой.
Таким образом, транслирование представляет собой преобразование массива низкой размерности в массив более высокой размерности для осуществления поэлементных операций.

Массивы NumPy — однородны (homogenous), то есть типы данных у всех значений массива одинаковы. Ниже представлен неполный список возможных типов данных массивов:
bool — булев тип данных в Python (1 байт);
int — целочисленный тип данных в Python (размер по умолчанию — 4 или 8 байт);
float — тип данных с плавающей точкой в Python (размер по умолчанию — 8 байт);
complex — тип данных для комплексных чисел в Python (размер по умолчанию — 16 байт);
np.int8 — целочисленный тип данных (1 байт);
np.int16 — целочисленный тип данных (2 байта);
np.int32 — целочисленный тип данных (4 байта);
np.int64 — целочисленный тип данных (8 байт);
np.float16 — тип данных с плавающей точкой (2 байта);
np.float32 — тип данных с плавающей точкой (4 байта);
np.float64 — тип данных с плавающей точкой (8 байт)

In [12]:
a = np.array([1, 2, 3, 4], dtype = np.int16)
print(a, a.dtype)


[1 2 3 4] int16


In [11]:
b = np.array([1, 2 ,3 , 4], dtype = np.float64)
print(b, b.dtype)

[1. 2. 3. 4.] float64


Итак, имеются данные по многим специальностям, и нужно повышать зарплаты одних только исследователей данных на 10 % раз в два года

In [14]:
## Данные: годовые зарплаты в тысячах долларов (за 2025, 2026 и 2027 гг.)
dataScientist = [130, 132, 137]
productManager = [127, 140, 145]
designer = [118, 118, 127]
softwareEngineer = [129, 131, 137]
employes = np.array([dataScientist,
                     productManager,
                     designer,
                     softwareEngineer])

employes[0, ::2] = employes[0, ::2] * 1.1
#сначала обращаемся к строке 0, 
#после идем по столбцам с интервалом в 2
print(employes)

[143 150]
[[143 132 150]
 [127 140 145]
 [118 118 127]
 [129 131 137]]


Во-первых, мы воспользуемся срезами и присваиванием срезам. В этом примере с помощью среза мы извлечем каждое второе значение из первой строки массива NumPy employees. Далее выполним некоторые модификации и обновим каждое второе значение первой строки с помощью присваивания срезу. Синтаксис присваивания срезу не отличается от самого среза, за исключением одного важного нюанса: в этом случае срез указывается с левой стороны оператора присваивания. Соответствующие элементы будут заменены элементами, указанными справа от оператора присваивания. В представленном фрагменте кода мы заменяем содержимое первой строки массива NumPy обновленными данными о зарплатах.
Во-вторых, мы воспользуемся транслированием для автоматического исправления поэлементных операций над массивами NumPy различной формы. В нашем однострочнике левый операнд — массив NumPy, а правый — значение с плавающей точкой. Опять же, NumPy автоматически создает новый массив того же размера и размерности, что и массив слева от оператора присваивания, и заполняет его, по сути, копиями этого значения с плавающей точкой. Фактически NumPy производит вычисление наподобие следующего:
np.array([130 137]) * np.array([1.1, 1.1])
В-третьих, наверное, вы поняли, что тип данных результата — не float, а integer, даже если вы выполняете операции над числами с плавающей точкой. При создании массива NumPy понимает, что тот содержит только целочисленные значения, поэтому полагает, что массив должен быть типа integer. Никакие операции над массивом типа integer не меняют типа данных, вследствие чего NumPy будет округлять значения до целочисленных.